steps:
- name: 'docker.io/library/python:3.7'
  entrypoint: /bin/sh
  # Run pip install and pytest in the same build step
  # (pip packages won't be preserved in future steps!)
#  args: [-c, 'pip install -r requirements.txt', '&&', 'pytest']
  args: [-c, 'pytest']
  dir: '/'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'celo', '--trigger-http', '--runtime', 'python37', '--entry-point', 'get_index', '--source', 'https://source.developers.google.com/projects/celo-284808/repos/github_unitato_celo']
  #dir: '/'
